# Homework 1: Datatalks Zoomcamp 2024 Cohort
## Student Name: Shyam Gupta
### Submission Date: 9/23/2024

In [3]:
# Import NumPy and Pandas
import numpy as np
import pandas as pd

In [5]:
# Q1:What's the version of Pandas that you installed?
# Answer: 2.2.3
pd.__version__

'2.2.3'

In [93]:
# Q2: How many records are in the dataset?
# Answer: 2160 rows
df = pd.read_csv('laptops.csv')
df.shape[0]

2160

In [21]:
# Q3: How many laptop brands are presented in the dataset?
# Answer 27
df['Brand'].nunique()

27

In [49]:
# Q4: How many columns in the dataset have missing values?
# Answer: 3 columns have missing values (Storage Type, GPU and Screen)
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [42]:
# Q5: What's the maximum final price of Dell notebooks in the dataset?
# Answer: $3,936
print(df[df['Brand']=='Dell']['Final Price'].max())

3936.0


In [52]:
# Q6-1: Find the median value of Screen column in the dataset.
# Answer:15.6"
print(df['Screen'].median())

15.6


In [72]:
# Q6-2: Calculate the most frequent value of the Screen column.
# Answer: 15.6" is the most frequent value
df['Screen'].value_counts().nlargest(1)

Screen
15.6    1009
Name: count, dtype: int64

In [104]:
# Q6-3: Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step
df['Screen'] = df['Screen'].fillna(15.6)
print("Number of missing values in 'Screen' column is: ",df['Screen'].isnull().sum())

Number of missing values in 'Screen' column is:  0


In [108]:
# Q6-4: calculate the median value of Screen once again.
# Answer: 15.6, it has NOT changes
print(df['Screen'].median())

15.6


In [112]:
# Q7-1: Select all the "Innjoo" laptops from the dataset.
df_innjoo = df[df['Brand']=='Innjoo']
df_innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [113]:
# Q7-2: Select only columns RAM, Storage, Screen.
df_innjoo_3 = df_innjoo[['RAM','Storage','Screen']]
df_innjoo_3

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [115]:
# Q7-3: Get the underlying NumPy array. Let's call it X.
X = df_innjoo_3.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [120]:
# Q7-4: Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = (X.T).dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [125]:
# Q7-5: Compute the inverse of XTX.
print(np.linalg.inv(XTX))

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [127]:
# Q7-6: Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [131]:
# Q7-7: Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
w = (np.linalg.inv(XTX)).dot(X.T).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [134]:
# Q7-8: What's the sum of all the elements of the result?
# Answer: 91.30 (rounded)
print(w.sum())

91.29988062995753
